version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - gateway-service

  gateway-service:
    build:
      context: ./backend/gateway-service
    ports:
      - "5000:5000"
    depends_on:
      - auth-service
      - map-service
      - extraction-service
      - payment-service

  auth-service:
    build:
      context: ./backend/auth-service
    ports:
      - "5001:5000"

  map-service:
    build:
      context: ./backend/map-service
    ports:
      - "5002:5000"

  extraction-service:
    build:
      context: ./backend/extraction-service
    ports:
      - "5003:5000"

  payment-service:
    build:
      context: ./backend/payment-service
    ports:
      - "5004:5000"